# Generated by Django 4.1.1 on 2022-09-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, help_text='username of a user', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
