# Generated by Django 4.1.1 on 2022-09-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='User personal email address', max_length=254, null=True, unique=True),
        ),
    ]
